// src/app/components/shared/success-screen/success-screen.component.ts
import { Component, Input, OnInit, OnDestroy } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-success-screen',
  templateUrl: './success-screen.component.html',
  styleUrls: ['./success-screen.component.scss']
})
export class SuccessScreenComponent implements OnInit, OnDestroy {
  @Input() title!: string;
  @Input() operationId!: string;
  @Input() operationType!: 'compra' | 'venda';

  countdown: number = 5;
  private timer?: number;

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.timer = window.setInterval(() => {
      this.countdown--;
      if (this.countdown <= 0) {
        this.navigateToHome();
      }
    }, 1000);
  }

  ngOnDestroy(): void {
    if (this.timer) {
      clearInterval(this.timer);
    }
  }

  navigateToHome(): void {
    this.router.navigate(['/']);
  }

  navigateToTrack(): void {
    this.router.navigate(['/track']);
  }
}
<div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-50 flex flex-col">
  <main class="flex-grow flex items-center justify-center">
    <div class="max-w-lg w-full mx-auto px-4">
      <div class="bg-white shadow-lg rounded-lg overflow-hidden">
        <div class="p-8 text-center">
          <div class="flex justify-center mb-6">
            <div class="bg-green-100 p-4 rounded-full">
              <lucide-icon name="check-circle" class="h-16 w-16 text-green-600"></lucide-icon>
            </div>
          </div>
          
          <h2 class="text-2xl font-bold text-gray-900 mb-4">{{ title }}</h2>
          
          <div class="bg-gray-50 p-4 rounded-lg mb-6">
            <p class="text-gray-700 mb-1">ID da Operação:</p>
            <p class="text-xl font-semibold text-gray-900">{{ operationId }}</p>
          </div>
          
          <p class="text-gray-600 mb-6">
            Sua operação de {{ operationType }} foi processada com sucesso.
          </p>
          
          <div class="space-y-4">
            <button 
              class="btn-primary w-full"
              (click)="navigateToHome()"
            >
              Nova Operação
            </button>
            
            <button 
              class="btn-secondary w-full"
              (click)="navigateToTrack()"
            >
              Acompanhar Operações
            </button>
          </div>
          
          <p class="mt-6 text-sm text-gray-500">
            Redirecionando para a página inicial em {{ countdown }} segundos...
          </p>
        </div>
      </div>
    </div>
  </main>
</div>

// src/components/shared/SuccessScreen.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { CheckCircle } from 'lucide-react';

interface SuccessScreenProps {
  title: string;
  operationId: string;
  operationType: 'compra' | 'venda';
}

const SuccessScreen = ({ title, operationId, operationType }: SuccessScreenProps) => {
  const navigate = useNavigate();
  const [countdown, setCountdown] = useState(5);
  
  useEffect(() => {
    const timer = setInterval(() => {
      setCountdown(prev => {
        if (prev <= 1) {
          clearInterval(timer);
          navigate('/');
          return 0;
        }
        return prev - 1;
      });
    }, 1000);
    
    return () => clearInterval(timer);
  }, [navigate]);
  
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-50 flex flex-col">
      <main className="flex-grow flex items-center justify-center">
        <div className="max-w-lg w-full mx-auto px-4">
          <div className="bg-white shadow-lg rounded-lg overflow-hidden">
            <div className="p-8 text-center">
              <div className="flex justify-center mb-6">
                <div className="bg-green-100 p-4 rounded-full">
                  <CheckCircle className="h-16 w-16 text-green-600" />
                </div>
              </div>
              
              <h2 className="text-2xl font-bold text-gray-900 mb-4">{title}</h2>
              
              <div className="bg-gray-50 p-4 rounded-lg mb-6">
                <p className="text-gray-700 mb-1">ID da Operação:</p>
                <p className="text-xl font-semibold text-gray-900">{operationId}</p>
              </div>
              
              <p className="text-gray-600 mb-6">
                Sua operação de {operationType} foi processada com sucesso.
              </p>
              
              <div className="space-y-4">
                <button 
                  className="btn-primary w-full"
                  onClick={() => navigate('/')}
                >
                  Nova Operação
                </button>
                
                <button 
                  className="btn-secondary w-full"
                  onClick={() => navigate('/track')}
                >
                  Acompanhar Operações
                </button>
              </div>
              
              <p className="mt-6 text-sm text-gray-500">
                Redirecionando para a página inicial em {countdown} segundos...
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default SuccessScreen;
