// src/components/UI/CurrencyInput.tsx
import { ChangeEvent } from 'react';

interface CurrencyInputProps {
  id: string;
  value: number | string;
  onChange: (value: number) => void;
  placeholder?: string;
  currencySymbol?: string;
  className?: string;
  disabled?: boolean;
}

const CurrencyInput = ({
  id,
  value,
  onChange,
  placeholder = '0,00',
  currencySymbol = '',
  className = '',
  disabled = false
}: CurrencyInputProps) => {
  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    // Remove any non-numeric characters except comma and period
    let rawValue = e.target.value.replace(/[^\d,.]/g, '');
    
    // Replace comma with period for calculation
    rawValue = rawValue.replace(',', '.');
    
    // Ensure only one decimal separator
    const parts = rawValue.split('.');
    if (parts.length > 2) {
      rawValue = parts[0] + '.' + parts.slice(1).join('');
    }
    
    // Convert to number
    const numValue = parseFloat(rawValue);
    
    if (!isNaN(numValue)) {
      // Limit to 2 decimal places
      const roundedValue = Math.round(numValue * 100) / 100;
      onChange(roundedValue);
    } else if (rawValue === '' || rawValue === '.' || rawValue === ',') {
      onChange(0);
    }
  };

  const formattedValue = value
    ? typeof value === 'number'
      ? value.toLocaleString('pt-BR', { 
          minimumFractionDigits: 2, 
          maximumFractionDigits: 2,
          useGrouping: true 
        })
      : value
    : '';

  return (
    <div className="relative">
      {currencySymbol && (
        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <span className="text-gray-500 sm:text-sm">{currencySymbol}</span>
        </div>
      )}
      <input
        id={id}
        type="text"
        value={formattedValue}
        onChange={handleChange}
        placeholder={placeholder}
        className={`form-input ${currencySymbol ? 'pl-7' : ''} ${className}`}
        disabled={disabled}
      />
    </div>
  );
};

export default CurrencyInput;

// src/app/components/shared/currency-input/currency-input.component.ts
import { Component, Input, Output, EventEmitter, forwardRef } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
  selector: 'app-currency-input',
  templateUrl: './currency-input.component.html',
  styleUrls: ['./currency-input.component.scss'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => CurrencyInputComponent),
      multi: true
    }
  ]
})
export class CurrencyInputComponent implements ControlValueAccessor {
  @Input() id!: string;
  @Input() placeholder: string = '0,00';
  @Input() currencySymbol: string = '';
  @Input() className: string = '';
  @Input() disabled: boolean = false;

  value: number = 0;
  displayValue: string = '';

  private onChange = (value: number) => {};
  private onTouched = () => {};

  onInput(event: Event): void {
    const target = event.target as HTMLInputElement;
    let rawValue = target.value.replace(/[^\d,.]/g, '');
    
    rawValue = rawValue.replace(',', '.');
    
    const parts = rawValue.split('.');
    if (parts.length > 2) {
      rawValue = parts[0] + '.' + parts.slice(1).join('');
    }
    
    const numValue = parseFloat(rawValue);
    
    if (!isNaN(numValue)) {
      const roundedValue = Math.round(numValue * 100) / 100;
      this.setValue(roundedValue);
    } else if (rawValue === '' || rawValue === '.' || rawValue === ',') {
      this.setValue(0);
    }
  }

  private setValue(value: number): void {
    this.value = value;
    this.displayValue = value ? value.toLocaleString('pt-BR', { 
      minimumFractionDigits: 2, 
      maximumFractionDigits: 2,
      useGrouping: true 
    }) : '';
    this.onChange(value);
  }

  writeValue(value: number): void {
    this.value = value || 0;
    this.displayValue = this.value ? this.value.toLocaleString('pt-BR', { 
      minimumFractionDigits: 2, 
      maximumFractionDigits: 2,
      useGrouping: true 
    }) : '';
  }

  registerOnChange(fn: (value: number) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }
}
<div class="relative">
  <div *ngIf="currencySymbol" class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
    <span class="text-gray-500 sm:text-sm">{{ currencySymbol }}</span>
  </div>
  <input
    [id]="id"
    type="text"
    [value]="displayValue"
    (input)="onInput($event)"
    (blur)="onTouched()"
    [placeholder]="placeholder"
    [class]="'form-input ' + (currencySymbol ? 'pl-7 ' : '') + className"
    [disabled]="disabled"
  />
</div>
