// src/components/UI/Card.tsx
import { ReactNode } from 'react';

interface CardProps {
  title?: string;
  children: ReactNode;
  className?: string;
}

const Card = ({ title, children, className = '' }: CardProps) => {
  return (
    <div className={`card ${className}`}>
      {title && <h3 className="text-lg font-medium mb-4 pb-2 border-b border-gray-200">{title}</h3>}
      {children}
    </div>
  );
};

export default Card;

// src/app/components/shared/card/card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.scss']
})
export class CardComponent {
  @Input() title?: string;
  @Input() className: string = '';
}
<div [class]="'card ' + className">
  <h3 *ngIf="title" class="text-lg font-medium mb-4 pb-2 border-b border-gray-200">{{ title }}</h3>
  <ng-content></ng-content>
</div>
