// src/app/components/shared/form-field/form-field.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-form-field',
  templateUrl: './form-field.component.html',
  styleUrls: ['./form-field.component.scss']
})
export class FormFieldComponent {
  @Input() id!: string;
  @Input() label!: string;
  @Input() required: boolean = false;
  @Input() helpText?: string;
  @Input() className: string = '';
}
<div [class]="'form-group ' + className">
  <label [for]="id" class="form-label">
    {{ label }}
    <span *ngIf="required" class="text-red-500 ml-1">*</span>
  </label>
  <ng-content></ng-content>
  <p *ngIf="helpText" class="mt-1 text-sm text-gray-500">{{ helpText }}</p>
</div>

// src/components/UI/FormField.tsx
import { ReactNode } from 'react';

interface FormFieldProps {
  id: string;
  label: string;
  children: ReactNode;
  className?: string;
  required?: boolean;
  helpText?: string;
}

const FormField = ({ id, label, children, className = '', required = false, helpText }: FormFieldProps) => {
  return (
    <div className={`form-group ${className}`}>
      <label htmlFor={id} className="form-label">
        {label}
        {required && <span className="text-red-500 ml-1">*</span>}
      </label>
      {children}
      {helpText && (
        <p className="mt-1 text-sm text-gray-500">{helpText}</p>
      )}
    </div>
  );
};

export default FormField;
