// src/app/components/shared/percentage-input/percentage-input.component.ts
import { Component, Input, forwardRef } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
  selector: 'app-percentage-input',
  templateUrl: './percentage-input.component.html',
  styleUrls: ['./percentage-input.component.scss'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => PercentageInputComponent),
      multi: true
    }
  ]
})
export class PercentageInputComponent implements ControlValueAccessor {
  @Input() id!: string;
  @Input() placeholder: string = '0.00';
  @Input() className: string = '';
  @Input() disabled: boolean = false;

  value: number = 0;
  displayValue: string = '';

  private onChange = (value: number) => {};
  private onTouched = () => {};

  onInput(event: Event): void {
    const target = event.target as HTMLInputElement;
    const rawValue = target.value.replace(/[^0-9.]/g, '');
    const numValue = parseFloat(rawValue);
    
    if (!isNaN(numValue)) {
      this.setValue(numValue);
    } else if (rawValue === '' || rawValue === '.') {
      this.setValue(0);
    }
  }

  private setValue(value: number): void {
    this.value = value;
    this.displayValue = value ? value.toLocaleString('pt-BR', { 
      minimumFractionDigits: 2, 
      maximumFractionDigits: 2 
    }) : '';
    this.onChange(value);
  }

  writeValue(value: number): void {
    this.value = value || 0;
    this.displayValue = this.value ? this.value.toLocaleString('pt-BR', { 
      minimumFractionDigits: 2, 
      maximumFractionDigits: 2 
    }) : '';
  }

  registerOnChange(fn: (value: number) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }
}
<div class="relative">
  <input
    [id]="id"
    type="text"
    [value]="displayValue"
    (input)="onInput($event)"
    (blur)="onTouched()"
    [placeholder]="placeholder"
    [class]="'form-input pr-7 ' + className"
    [disabled]="disabled"
  />
  <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
    <span class="text-gray-500 sm:text-sm">%</span>
  </div>
</div>

// src/components/UI/PercentageInput.tsx
import { ChangeEvent } from 'react';

interface PercentageInputProps {
  id: string;
  value: number | string;
  onChange: (value: number) => void;
  placeholder?: string;
  className?: string;
  disabled?: boolean;
}

const PercentageInput = ({
  id,
  value,
  onChange,
  placeholder = '0.00',
  className = '',
  disabled = false
}: PercentageInputProps) => {
  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    const rawValue = e.target.value.replace(/[^0-9.]/g, '');
    const numValue = parseFloat(rawValue);
    
    if (!isNaN(numValue)) {
      onChange(numValue);
    } else if (rawValue === '' || rawValue === '.') {
      onChange(0);
    }
  };

  const formattedValue = value
    ? typeof value === 'number'
      ? value.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
      : value
    : '';

  return (
    <div className="relative">
      <input
        id={id}
        type="text"
        value={formattedValue}
        onChange={handleChange}
        placeholder={placeholder}
        className={`form-input pr-7 ${className}`}
        disabled={disabled}
      />
      <div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
        <span className="text-gray-500 sm:text-sm">%</span>
      </div>
    </div>
  );
};

export default PercentageInput;
